// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2BjSyBMgGQyWEo2L7CpuLliMo50xiB0',
    appId: '1:190998421033:web:9e0f1d0d6982eac328c638',
    messagingSenderId: '190998421033',
    projectId: 'love-message-2835b',
    authDomain: 'love-message-2835b.firebaseapp.com',
    storageBucket: 'love-message-2835b.firebasestorage.app',
    measurementId: 'G-YLZWVNGE02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDCWiwdOFcKoQjScNM65k6-iLhElFLRk',
    appId: '1:190998421033:android:3a00fc5ab8a2338528c638',
    messagingSenderId: '190998421033',
    projectId: 'love-message-2835b',
    storageBucket: 'love-message-2835b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6JZyXZS3HciZ2SXt8aSmUrBWahx56Fv0',
    appId: '1:190998421033:ios:c9a472f403ae307e28c638',
    messagingSenderId: '190998421033',
    projectId: 'love-message-2835b',
    storageBucket: 'love-message-2835b.firebasestorage.app',
    iosBundleId: 'com.coeuracoeur.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6JZyXZS3HciZ2SXt8aSmUrBWahx56Fv0',
    appId: '1:190998421033:ios:e8c60d28d21047a828c638',
    messagingSenderId: '190998421033',
    projectId: 'love-message-2835b',
    storageBucket: 'love-message-2835b.firebasestorage.app',
    iosBundleId: 'com.example.loveMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf2BjSyBMgGQyWEo2L7CpuLliMo50xiB0',
    appId: '1:190998421033:web:8c4c64e6dbc9555b28c638',
    messagingSenderId: '190998421033',
    projectId: 'love-message-2835b',
    authDomain: 'love-message-2835b.firebaseapp.com',
    storageBucket: 'love-message-2835b.firebasestorage.app',
    measurementId: 'G-XMS2B9CR5H',
  );
}
